In [6]:
import sqlite3
conn = sqlite3.connect("../data/msft_customers.db")
cursor = conn.cursor()

In [7]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables names:", tables)

Tables names: [('ErrorLog',), ('sqlite_sequence',), ('BuildVersion',), ('Address',), ('Customer',), ('CustomerAddress',), ('Product',), ('ProductCategory',), ('ProductDescription',), ('ProductModel',), ('ProductModelProductDescription',), ('SalesOrderDetail',), ('SalesOrderHeader',)]

In [8]:
for table_name, in tables:
    print(f"\nSchema for table '{table_name}':")
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    for col in columns:
        # (cid, name, type, notnull, dflt_value, pk)
        print(f"  {col[1]} ({col[2]})") # print name and type

Schema for table 'ErrorLog':
  ErrorLogID (INTEGER)
  ErrorTime (DATETIME)
  UserName (TEXT)
  ErrorNumber (INTEGER)
  ErrorSeverity (INTEGER)
  ErrorState (INTEGER)
  ErrorProcedure (TEXT)
  ErrorLine (INTEGER)
  ErrorMessage (TEXT)

Schema for table 'sqlite_sequence':
  name ()
  seq ()

Schema for table 'BuildVersion':
  SystemInformationID (INTEGER)
  Database Version (TEXT)
  VersionDate (DATETIME)
  ModifiedDate (DATETIME)

Schema for table 'Address':
  AddressID (INTEGER)
  AddressLine1 (TEXT)
  AddressLine2 (TEXT)
  City (TEXT)
  StateProvince (TEXT)
  CountryRegion (TEXT)
  PostalCode (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'Customer':
  CustomerID (INTEGER)
  NameStyle (INTEGER)
  Title (TEXT)
  FirstName (TEXT)
  MiddleName (TEXT)
  LastName (TEXT)
  Suffix (TEXT)
  CompanyName (TEXT)
  SalesPerson (TEXT)
  EmailAddress (TEXT)
  Phone (TEXT)
  PasswordHash (TEXT)
  PasswordSalt (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'CustomerAddress':
  CustomerID (INTEGER)
  AddressID (INTEGER)
  AddressType (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'Product':
  ProductID (INTEGER)
  Name (TEXT)
  ProductNumber (TEXT)
  Color (TEXT)
  StandardCost (INTEGER)
  ListPrice (INTEGER)
  Size (TEXT)
  Weight (INTEGER)
  ProductCategoryID (INTEGER)
  ProductModelID (INTEGER)
  SellStartDate (DATETIME)
  SellEndDate (DATETIME)
  DiscontinuedDate (DATETIME)
  ThumbNailPhoto (BLOB)
  ThumbnailPhotoFileName (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'ProductCategory':
  ProductCategoryID (INTEGER)
  ParentProductCategoryID (INTEGER)
  Name (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'ProductDescription':
  ProductDescriptionID (INTEGER)
  Description (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'ProductModel':
  ProductModelID (INTEGER)
  Name (TEXT)
  CatalogDescription (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'ProductModelProductDescription':
  ProductModelID (INTEGER)
  ProductDescriptionID (INTEGER)
  Culture (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'SalesOrderDetail':
  SalesOrderID (INTEGER)
  SalesOrderDetailID (INTEGER IDENTITY (1, 1))
  OrderQty (INTEGER)
  ProductID (INTEGER)
  UnitPrice (INTEGER)
  UnitPriceDiscount (INTEGER)
  LineTotal (INTEGER)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

Schema for table 'SalesOrderHeader':
  SalesOrderID (INTEGER)
  RevisionNumber (INTEGER)
  OrderDate (DATETIME)
  DueDate (DATETIME)
  ShipDate (DATETIME)
  Status (INTEGER)
  OnlineOrderFlag (INTEGER)
  SalesOrderNumber (TEXT)
  PurchaseOrderNumber (INTEGER)
  AccountNumber (TEXT)
  CustomerID (INTEGER)
  ShipToAddressID (INT)
  BillToAddressID (INT)
  ShipMethod (TEXT)
  CreditCardApprovalCode (TEXT)
  SubTotal (INTEGER)
  TaxAmt (INTEGER)
  Freight (INTEGER)
  TotalDue (INTEGER)
  Comment (TEXT)
  rowguid (TEXT)
  ModifiedDate (DATETIME)

In [ ]:
# SELECT * FROM customer c join "CustomerAddress" ca on c."CustomerID" = ca."CustomerID"  join address a on ca."AddressID" = a."AddressID" join salesorderheader s on s."CustomerID" = c."CustomerID" LIMIT 100

In [9]:
import sqlite3

def describe_table_schema(cursor, table_name):
    print(f"\nðŸ“„ Table: {table_name}")

    # Column info
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    print("  Columns:")
    for col in columns:
        cid, name, dtype, notnull, dflt_value, pk = col
        pk_flag = "PRIMARY KEY" if pk else ""
        print(f"    - {name} ({dtype}) {'NOT NULL' if notnull else ''} {pk_flag}")

    # Foreign key info
    cursor.execute(f"PRAGMA foreign_key_list({table_name});")
    fks = cursor.fetchall()
    if fks:
        print("  Foreign Keys:")
        for fk in fks:
            id_, seq, ref_table, from_col, to_col, on_update, on_delete, match = fk
            print(f"    - {from_col} â†’ {ref_table}({to_col}) [on_delete={on_delete}, on_update={on_update}]")
    else:
        print("  Foreign Keys: None")

def inspect_sqlite_schema(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Get all tables (excluding internal sqlite tables)
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
    tables = [row[0] for row in cursor.fetchall()]

    print(f"\nðŸ“š Found {len(tables)} user-defined tables in {db_path}:")

    for table in tables:
        describe_table_schema(cursor, table)

    conn.close()

# Replace this path with your actual SQLite DB path
db_file = "../data/msft_customers.db"
inspect_sqlite_schema(db_file)

ðŸ“š Found 12 user-defined tables in ../data/msft_customers.db:

ðŸ“„ Table: ErrorLog
  Columns:
    - ErrorLogID (INTEGER)  PRIMARY KEY
    - ErrorTime (DATETIME) NOT NULL
    - UserName (TEXT) NOT NULL
    - ErrorNumber (INTEGER) NOT NULL
    - ErrorSeverity (INTEGER)
    - ErrorState (INTEGER)
    - ErrorProcedure (TEXT)
    - ErrorLine (INTEGER)
    - ErrorMessage (TEXT) NOT NULL
  Foreign Keys: None

ðŸ“„ Table: BuildVersion
  Columns:
    - SystemInformationID (INTEGER)  PRIMARY KEY
    - Database Version (TEXT) NOT NULL
    - VersionDate (DATETIME) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys: None

ðŸ“„ Table: Address
  Columns:
    - AddressID (INTEGER)  PRIMARY KEY
    - AddressLine1 (TEXT) NOT NULL
    - AddressLine2 (TEXT)
    - City (TEXT) NOT NULL
    - StateProvince (TEXT) NOT NULL
    - CountryRegion (TEXT) NOT NULL
    - PostalCode (TEXT) NOT NULL
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys: None

ðŸ“„ Table: Customer
  Columns:
    - CustomerID (INTEGER)  PRIMARY KEY
    - NameStyle (INTEGER) NOT NULL
    - Title (TEXT)
    - FirstName (TEXT) NOT NULL
    - MiddleName (TEXT)
    - LastName (TEXT) NOT NULL
    - Suffix (TEXT)
    - CompanyName (TEXT)
    - SalesPerson (TEXT)
    - EmailAddress (TEXT)
    - Phone (TEXT)
    - PasswordHash (TEXT) NOT NULL
    - PasswordSalt (TEXT) NOT NULL
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys: None

ðŸ“„ Table: CustomerAddress
  Columns:
    - CustomerID (INTEGER) NOT NULL PRIMARY KEY
    - AddressID (INTEGER) NOT NULL PRIMARY KEY
    - AddressType (TEXT) NOT NULL
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys:
    - AddressID â†’ Address(AddressID) [on_delete=NO ACTION, on_update=NO ACTION]
    - CustomerID â†’ Customer(CustomerID) [on_delete=NO ACTION, on_update=NO ACTION]

ðŸ“„ Table: Product
  Columns:
    - ProductID (INTEGER)  PRIMARY KEY
    - Name (TEXT) NOT NULL
    - ProductNumber (TEXT) NOT NULL
    - Color (TEXT)
    - StandardCost (INTEGER) NOT NULL
    - ListPrice (INTEGER) NOT NULL
    - Size (TEXT)
    - Weight (INTEGER)
    - ProductCategoryID (INTEGER)
    - ProductModelID (INTEGER)
    - SellStartDate (DATETIME) NOT NULL
    - SellEndDate (DATETIME)
    - DiscontinuedDate (DATETIME)
    - ThumbNailPhoto (BLOB)
    - ThumbnailPhotoFileName (TEXT)
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys:
    - ProductCategoryID â†’ ProductCategory(ProductCategoryID) [on_delete=NO ACTION, on_update=NO ACTION]
    - ProductModelID â†’ ProductModel(ProductModelID) [on_delete=NO ACTION, on_update=NO ACTION]

ðŸ“„ Table: ProductCategory
  Columns:
    - ProductCategoryID (INTEGER)  PRIMARY KEY
    - ParentProductCategoryID (INTEGER)
    - Name (TEXT) NOT NULL
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys:
    - ParentProductCategoryID â†’ ProductCategory(ProductCategoryID) [on_delete=NO ACTION, on_update=NO ACTION]

ðŸ“„ Table: ProductDescription
  Columns:
    - ProductDescriptionID (INTEGER)  PRIMARY KEY
    - Description (TEXT) NOT NULL
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys: None

ðŸ“„ Table: ProductModel
  Columns:
    - ProductModelID (INTEGER)  PRIMARY KEY
    - Name (TEXT) NOT NULL
    - CatalogDescription (TEXT)
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys: None

ðŸ“„ Table: ProductModelProductDescription
  Columns:
    - ProductModelID (INTEGER) NOT NULL PRIMARY KEY
    - ProductDescriptionID (INTEGER) NOT NULL PRIMARY KEY
    - Culture (TEXT) NOT NULL PRIMARY KEY
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys:
    - ProductModelID â†’ ProductModel(ProductModelID) [on_delete=NO ACTION, on_update=NO ACTION]
    - ProductDescriptionID â†’ ProductDescription(ProductDescriptionID) [on_delete=NO ACTION, on_update=NO ACTION]

ðŸ“„ Table: SalesOrderDetail
  Columns:
    - SalesOrderID (INTEGER) NOT NULL PRIMARY KEY
    - SalesOrderDetailID (INTEGER IDENTITY (1, 1)) NOT NULL PRIMARY KEY
    - OrderQty (INTEGER) NOT NULL
    - ProductID (INTEGER) NOT NULL
    - UnitPrice (INTEGER) NOT NULL
    - UnitPriceDiscount (INTEGER) NOT NULL
    - LineTotal (INTEGER) NOT NULL
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys:
    - ProductID â†’ Product(ProductID) [on_delete=NO ACTION, on_update=NO ACTION]
    - SalesOrderID â†’ SalesOrderHeader(SalesOrderID) [on_delete=NO ACTION, on_update=NO ACTION]

ðŸ“„ Table: SalesOrderHeader
  Columns:
    - SalesOrderID (INTEGER)  PRIMARY KEY
    - RevisionNumber (INTEGER) NOT NULL
    - OrderDate (DATETIME) NOT NULL
    - DueDate (DATETIME) NOT NULL
    - ShipDate (DATETIME)
    - Status (INTEGER) NOT NULL
    - OnlineOrderFlag (INTEGER) NOT NULL
    - SalesOrderNumber (TEXT) NOT NULL
    - PurchaseOrderNumber (INTEGER)
    - AccountNumber (TEXT)
    - CustomerID (INTEGER) NOT NULL
    - ShipToAddressID (INT)
    - BillToAddressID (INT)
    - ShipMethod (TEXT) NOT NULL
    - CreditCardApprovalCode (TEXT)
    - SubTotal (INTEGER) NOT NULL
    - TaxAmt (INTEGER) NOT NULL
    - Freight (INTEGER) NOT NULL
    - TotalDue (INTEGER) NOT NULL
    - Comment (TEXT)
    - rowguid (TEXT) NOT NULL
    - ModifiedDate (DATETIME) NOT NULL
  Foreign Keys:
    - BillToAddressID â†’ Address(AddressID) [on_delete=NO ACTION, on_update=NO ACTION]
    - ShipToAddressID â†’ Address(AddressID) [on_delete=NO ACTION, on_update=NO ACTION]
    - CustomerID â†’ Customer(CustomerID) [on_delete=NO ACTION, on_update=NO ACTION]

In [10]:
for table_name, in tables:
    cursor.execute(f"SELECT * FROM {table_name} LIMIT 5;")
    rows = cursor.fetchall()
    print(f"\n{table_name} Example rows:")
    for row in rows:
        print(f"    {row}")

ErrorLog Example rows:

sqlite_sequence Example rows:
    ('BuildVersion', 1)
    ('Customer', 30118)
    ('Product', 999)
    ('ProductCategory', 41)
    ('ProductDescription', 2010)

BuildVersion Example rows:
    (1, '10.50.91013.00', '2009-10-13 00:00:00.000', '2009-10-13 00:00:00.000')

Address Example rows:
    (9, '8713 Yosemite Ct.', '', 'Bothell', 'Washington', 'United States', '98011', '268AF621-76D7-4C78-9441-144FD139821A', '2006-07-01 00:00:00.000')
    (11, '1318 Lasalle Street', '', 'Bothell', 'Washington', 'United States', '98011', '981B3303-ACA2-49C7-9A96-FB670785B269', '2007-04-01 00:00:00.000')
    (25, '9178 Jumping St.', '', 'Dallas', 'Texas', 'United States', '75201', 'C8DF3BD9-48F0-4654-A8DD-14A67A84D3C6', '2006-09-01 00:00:00.000')
    (28, '9228 Via Del Sol', '', 'Phoenix', 'Arizona', 'United States', '85004', '12AE5EE1-FC3E-468B-9B92-3B970B169774', '2005-09-01 00:00:00.000')
    (32, '26910 Indela Road', '', 'Montreal', 'Quebec', 'Canada', 'H1Y 2H5', '84A95F62-3AE8-4E7E-BBD5-5A6F00CD982D', '2006-08-01 00:00:00.000')

Customer Example rows:
    (1, 0, 'Mr.', 'Orlando', 'N.', 'Gee', '', 'A Bike Store', 'adventure-works\\pamela0', 'orlando0@adventure-works.com', '245-555-0173', 'L/Rlwxzp4w7RWmEgXX+/A7cXaePEPcp+KwQhl2fJL7w=', '1KjXYs4=', '3F5AE95E-B87D-4AED-95B4-C3797AFCB74F', '2005-08-01 00:00:00.000')
    (2, 0, 'Mr.', 'Keith', '', 'Harris', '', 'Progressive Sports', 'adventure-works\\david8', 'keith0@adventure-works.com', '170-555-0127', 'YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=', 'fs1ZGhY=', 'E552F657-A9AF-4A7D-A645-C429D6E02491', '2006-08-01 00:00:00.000')
    (3, 0, 'Ms.', 'Donna', 'F.', 'Carreras', '', 'Advanced Bike Components', 'adventure-works\\jillian0', 'donna0@adventure-works.com', '279-555-0130', 'LNoK27abGQo48gGue3EBV/UrlYSToV0/s87dCRV7uJk=', 'YTNH5Rw=', '130774B1-DB21-4EF3-98C8-C104BCD6ED6D', '2005-09-01 00:00:00.000')
    (4, 0, 'Ms.', 'Janet', 'M.', 'Gates', '', 'Modular Cycle Systems', 'adventure-works\\jillian0', 'janet1@adventure-works.com', '710-555-0173', 'ElzTpSNbUW1Ut+L5cWlfR7MF6nBZia8WpmGaQPjLOJA=', 'nm7D5e4=', 'FF862851-1DAA-4044-BE7C-3E85583C054D', '2006-07-01 00:00:00.000')
    (5, 0, 'Mr.', 'Lucy', '', 'Harrington', '', 'Metropolitan Sports Supply', 'adventure-works\\shu0', 'lucy0@adventure-works.com', '828-555-0186', 'KJqV15wsX3PG8TS5GSddp6LFFVdd3CoRftZM/tP0+R4=', 'cNFKU4w=', '83905BDC-6F5E-4F71-B162-C98DA069F38A', '2006-09-01 00:00:00.000')

CustomerAddress Example rows:
    (29485, 1086, 'Main Office', '16765338-DBE4-4421-B5E9-3836B9278E63', '2007-09-01 00:00:00.000')
    (29486, 621, 'Main Office', '22B3E910-14AF-4ED5-8B4D-23BBE757414D', '2005-09-01 00:00:00.000')
    (29489, 1069, 'Main Office', 'A095C88B-D7E6-4178-A078-2ECA44214801', '2005-07-01 00:00:00.000')
    (29490, 887, 'Main Office', 'F12E1702-D897-4035-B614-0FE2C72168A9', '2006-09-01 00:00:00.000')
    (29492, 618, 'Main Office', '5B3B3EB2-3F43-47ED-A20C-23697DABF23B', '2006-12-01 00:00:00.000')

Product Example rows:
    (680, 'HL Road Frame - Black, 58', 'FR-R92B-58', 'Black', 1059.31, 1431.5, '58', 1016.04, 18, 6, '2002-06-01 00:00:00.000', '', '', '47494638396150003100F70000000000800000008000808000000080800080008080808080C0C0C0FF000000FF00FFFF000000FFFF00FF00FFFFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000330000660000990000CC0000FF0033000033330033660033990033CC0033FF0066000066330066660066990066CC0066FF0099000099330099660099990099CC0099FF00CC0000CC3300CC6600CC9900CCCC00CCFF00FF0000FF3300FF6600FF9900FFCC00FFFF3300003300333300663300993300CC3300FF3333003333333333663333993333CC3333FF3366003366333366663366993366CC3366FF3399003399333399663399993399CC3399FF33CC0033CC3333CC6633CC9933CCCC33CCFF33FF0033FF3333FF6633FF9933FFCC33FFFF6600006600336600666600996600CC6600FF6633006633336633666633996633CC6633FF6666006666336666666666996666CC6666FF6699006699336699666699996699CC6699FF66CC0066CC3366CC6666CC9966CCCC66CCFF66FF0066FF3366FF6666FF9966FFCC66FFFF9900009900339900669900999900CC9900FF9933009933339933669933999933CC9933FF9966009966339966669966999966CC9966FF9999009999339999669999999999CC9999FF99CC0099CC3399CC6699CC9999CCCC99CCFF99FF0099FF3399FF6699FF9999FFCC99FFFFCC0000CC0033CC0066CC0099CC00CCCC00FFCC3300CC3333CC3366CC3399CC33CCCC33FFCC6600CC6633CC6666CC6699CC66CCCC66FFCC9900CC9933CC9966CC9999CC99CCCC99FFCCCC00CCCC33CCCC66CCCC99CCCCCCCCCCFFCCFF00CCFF33CCFF66CCFF99CCFFCCCCFFFFFF0000FF0033FF0066FF0099FF00CCFF00FFFF3300FF3333FF3366FF3399FF33CCFF33FFFF6600FF6633FF6666FF6699FF66CCFF66FFFF9900FF9933FF9966FF9999FF99CCFF99FFFFCC00FFCC33FFCC66FFCC99FFCCCCFFCCFFFFFF00FFFF33FFFF66FFFF99FFFFCCFFFFFF21F90401000010002C00000000500031000008FF00FF091C48B0A0C18308132A5CC8B0A1C38710234A9C48B1A2C58B18336ADCC8B1A3C78F20438A1C49B2A4C9932853AA5C9911058A812E17C664F9D0E5CB7F3313E6A4C9D0A6C099366FC27C19D367CEA04371DE44CA1169D1A542952A25FA1467D2A7547F46C558542AD0A855A58A9D9AD52BD4A654C3EE547BD6AC58AC3E377E2DBB96EED9AF6FCB7A9C9B97205BAD7DB1F6952B74EED6BF79E3B2DDC95362E1AD8D2F328D4CB9B2E5CB9831C77518D62063C6223743040DD82F6490558FA6BD0B152F5EB2A8B3AA7EEC96B651D96D3BFE9D8D7BE86EBB1F7F034ECD3AF06AD292831237EEB6F9F290AAB5B65DEE9A7A6EC249A7FA7EAEDC79EBD399C38B121F4FBEBCF9F3E8D3AB5FCFBEBDFBF7EF0302003B', 'no_image_available_small.gif', '43DD68D6-14A4-461F-9069-55309D90EA7E', '2008-03-11 10:01:36.827')
    (706, 'HL Road Frame - Red, 58', 'FR-R92R-58', 'Red', 1059.31, 1431.5, '58', 1016.04, 18, 6, '2002-06-01 00:00:00.000', '', '', '47494638396150003100F70000000000800000008000808000000080800080008080808080C0C0C0FF000000FF00FFFF000000FFFF00FF00FFFFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000330000660000990000CC0000FF0033000033330033660033990033CC0033FF0066000066330066660066990066CC0066FF0099000099330099660099990099CC0099FF00CC0000CC3300CC6600CC9900CCCC00CCFF00FF0000FF3300FF6600FF9900FFCC00FFFF3300003300333300663300993300CC3300FF3333003333333333663333993333CC3333FF3366003366333366663366993366CC3366FF3399003399333399663399993399CC3399FF33CC0033CC3333CC6633CC9933CCCC33CCFF33FF0033FF3333FF6633FF9933FFCC33FFFF6600006600336600666600996600CC6600FF6633006633336633666633996633CC6633FF6666006666336666666666996666CC6666FF6699006699336699666699996699CC6699FF66CC0066CC3366CC6666CC9966CCCC66CCFF66FF0066FF3366FF6666FF9966FFCC66FFFF9900009900339900669900999900CC9900FF9933009933339933669933999933CC9933FF9966009966339966669966999966CC9966FF9999009999339999669999999999CC9999FF99CC0099CC3399CC6699CC9999CCCC99CCFF99FF0099FF3399FF6699FF9999FFCC99FFFFCC0000CC0033CC0066CC0099CC00CCCC00FFCC3300CC3333CC3366CC3399CC33CCCC33FFCC6600CC6633CC6666CC6699CC66CCCC66FFCC9900CC9933CC9966CC9999CC99CCCC99FFCCCC00CCCC33CCCC66CCCC99CCCCCCCCCCFFCCFF00CCFF33CCFF66CCFF99CCFFCCCCFFFFFF0000FF0033FF0066FF0099FF00CCFF00FFFF3300FF3333FF3366FF3399FF33CCFF33FFFF6600FF6633FF6666FF6699FF66CCFF66FFFF9900FF9933FF9966FF9999FF99CCFF99FFFFCC00FFCC33FFCC66FFCC99FFCCCCFFCCFFFFFF00FFFF33FFFF66FFFF99FFFFCCFFFFFF21F90401000010002C00000000500031000008FF00FF091C48B0A0C18308132A5CC8B0A1C38710234A9C48B1A2C58B18336ADCC8B1A3C78F20438A1C49B2A4C9932853AA5C9911058A812E17C664F9D0E5CB7F3313E6A4C9D0A6C099366FC27C19D367CEA04371DE44CA1169D1A542952A25FA1467D2A7547F46C558542AD0A855A58A9D9AD52BD4A654C3EE547BD6AC58AC3E377E2DBB96EED9AF6FCB7A9C9B97205BAD7DB1F6952B74EED6BF79E3B2DDC95362E1AD8D2F328D4CB9B2E5CB9831C77518D62063C6223743040DD82F6490558FA6BD0B152F5EB2A8B3AA7EEC96B651D96D3BFE9D8D7BE86EBB1F7F034ECD3AF06AD292831237EEB6F9F290AAB5B65DEE9A7A6EC249A7FA7EAEDC79EBD399C38B121F4FBEBCF9F3E8D3AB5FCFBEBDFBF7EF0302003B', 'no_image_available_small.gif', '9540FF17-2712-4C90-A3D1-8CE5568B2462', '2008-03-11 10:01:36.827')
    (707, 'Sport-100 Helmet, Red', 'HL-U509-R', 'Red', 13.0863, 34.99, '', '', 35, 33, '2005-07-01 00:00:00.000', '', '', '47494638396150003100F70000000000800000008000808000000080800080008080808080C0C0C0FF000000FF00FFFF000000FFFF00FF00FFFFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000330000660000990000CC0000FF0033000033330033660033990033CC0033FF0066000066330066660066990066CC0066FF0099000099330099660099990099CC0099FF00CC0000CC3300CC6600CC9900CCCC00CCFF00FF0000FF3300FF6600FF9900FFCC00FFFF3300003300333300663300993300CC3300FF3333003333333333663333993333CC3333FF3366003366333366663366993366CC3366FF3399003399333399663399993399CC3399FF33CC0033CC3333CC6633CC9933CCCC33CCFF33FF0033FF3333FF6633FF9933FFCC33FFFF6600006600336600666600996600CC6600FF6633006633336633666633996633CC6633FF6666006666336666666666996666CC6666FF6699006699336699666699996699CC6699FF66CC0066CC3366CC6666CC9966CCCC66CCFF66FF0066FF3366FF6666FF9966FFCC66FFFF9900009900339900669900999900CC9900FF9933009933339933669933999933CC9933FF9966009966339966669966999966CC9966FF9999009999339999669999999999CC9999FF99CC0099CC3399CC6699CC9999CCCC99CCFF99FF0099FF3399FF6699FF9999FFCC99FFFFCC0000CC0033CC0066CC0099CC00CCCC00FFCC3300CC3333CC3366CC3399CC33CCCC33FFCC6600CC6633CC6666CC6699CC66CCCC66FFCC9900CC9933CC9966CC9999CC99CCCC99FFCCCC00CCCC33CCCC66CCCC99CCCCCCCCCCFFCCFF00CCFF33CCFF66CCFF99CCFFCCCCFFFFFF0000FF0033FF0066FF0099FF00CCFF00FFFF3300FF3333FF3366FF3399FF33CCFF33FFFF6600FF6633FF6666FF6699FF66CCFF66FFFF9900FF9933FF9966FF9999FF99CCFF99FFFFCC00FFCC33FFCC66FFCC99FFCCCCFFCCFFFFFF00FFFF33FFFF66FFFF99FFFFCCFFFFFF21F90401000010002C00000000500031000008FF00FF091C48B0A0C18308132A5CC8B0A1C38710234A9C48B1A2C58B18336ADCC8B1A3C78F20438A1C49B2A4C9932853AA5C9911058A812E17C664F9D0E5CB7F3313E6A4C9D0A6C099366FC27C19D367CEA04371DE44CA1169D1A542952A25FA1467D2A7547F46C558542AD0A855A58A9D9AD52BD4A654C3EE547BD6AC58AC3E377E2DBB96EED9AF6FCB7A9C9B97205BAD7DB1F6952B74EED6BF79E3B2DDC95362E1AD8D2F328D4CB9B2E5CB9831C77518D62063C6223743040DD82F6490558FA6BD0B152F5EB2A8B3AA7EEC96B651D96D3BFE9D8D7BE86EBB1F7F034ECD3AF06AD292831237EEB6F9F290AAB5B65DEE9A7A6EC249A7FA7EAEDC79EBD399C38B121F4FBEBCF9F3E8D3AB5FCFBEBDFBF7EF0302003B', 'no_image_available_small.gif', '2E1EF41A-C08A-4FF6-8ADA-BDE58B64A712', '2008-03-11 10:01:36.827')
    (708, 'Sport-100 Helmet, Black', 'HL-U509', 'Black', 13.0863, 34.99, '', '', 35, 33, '2005-07-01 00:00:00.000', '', '', '47494638396150003100F70000000000800000008000808000000080800080008080808080C0C0C0FF000000FF00FFFF000000FFFF00FF00FFFFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000330000660000990000CC0000FF0033000033330033660033990033CC0033FF0066000066330066660066990066CC0066FF0099000099330099660099990099CC0099FF00CC0000CC3300CC6600CC9900CCCC00CCFF00FF0000FF3300FF6600FF9900FFCC00FFFF3300003300333300663300993300CC3300FF3333003333333333663333993333CC3333FF3366003366333366663366993366CC3366FF3399003399333399663399993399CC3399FF33CC0033CC3333CC6633CC9933CCCC33CCFF33FF0033FF3333FF6633FF9933FFCC33FFFF6600006600336600666600996600CC6600FF6633006633336633666633996633CC6633FF6666006666336666666666996666CC6666FF6699006699336699666699996699CC6699FF66CC0066CC3366CC6666CC9966CCCC66CCFF66FF0066FF3366FF6666FF9966FFCC66FFFF9900009900339900669900999900CC9900FF9933009933339933669933999933CC9933FF9966009966339966669966999966CC9966FF9999009999339999669999999999CC9999FF99CC0099CC3399CC6699CC9999CCCC99CCFF99FF0099FF3399FF6699FF9999FFCC99FFFFCC0000CC0033CC0066CC0099CC00CCCC00FFCC3300CC3333CC3366CC3399CC33CCCC33FFCC6600CC6633CC6666CC6699CC66CCCC66FFCC9900CC9933CC9966CC9999CC99CCCC99FFCCCC00CCCC33CCCC66CCCC99CCCCCCCCCCFFCCFF00CCFF33CCFF66CCFF99CCFFCCCCFFFFFF0000FF0033FF0066FF0099FF00CCFF00FFFF3300FF3333FF3366FF3399FF33CCFF33FFFF6600FF6633FF6666FF6699FF66CCFF66FFFF9900FF9933FF9966FF9999FF99CCFF99FFFFCC00FFCC33FFCC66FFCC99FFCCCCFFCCFFFFFF00FFFF33FFFF66FFFF99FFFFCCFFFFFF21F90401000010002C00000000500031000008FF00FF091C48B0A0C18308132A5CC8B0A1C38710234A9C48B1A2C58B18336ADCC8B1A3C78F20438A1C49B2A4C9932853AA5C9911058A812E17C664F9D0E5CB7F3313E6A4C9D0A6C099366FC27C19D367CEA04371DE44CA1169D1A542952A25FA1467D2A7547F46C558542AD0A855A58A9D9AD52BD4A654C3EE547BD6AC58AC3E377E2DBB96EED9AF6FCB7A9C9B97205BAD7DB1F6952B74EED6BF79E3B2DDC95362E1AD8D2F328D4CB9B2E5CB9831C77518D62063C6223743040DD82F6490558FA6BD0B152F5EB2A8B3AA7EEC96B651D96D3BFE9D8D7BE86EBB1F7F034ECD3AF06AD292831237EEB6F9F290AAB5B65DEE9A7A6EC249A7FA7EAEDC79EBD399C38B121F4FBEBCF9F3E8D3AB5FCFBEBDFBF7EF0302003B', 'no_image_available_small.gif', 'A25A44FB-C2DE-4268-958F-110B8D7621E2', '2008-03-11 10:01:36.827')
    (709, 'Mountain Bike Socks, M', 'SO-B909-M', 'White', 3.3963, 9.5, 'M', '', 27, 18, '2005-07-01 00:00:00.000', '2006-06-30 00:00:00.000', '', '47494638396150003100F70000000000800000008000808000000080800080008080808080C0C0C0FF000000FF00FFFF000000FFFF00FF00FFFFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000330000660000990000CC0000FF0033000033330033660033990033CC0033FF0066000066330066660066990066CC0066FF0099000099330099660099990099CC0099FF00CC0000CC3300CC6600CC9900CCCC00CCFF00FF0000FF3300FF6600FF9900FFCC00FFFF3300003300333300663300993300CC3300FF3333003333333333663333993333CC3333FF3366003366333366663366993366CC3366FF3399003399333399663399993399CC3399FF33CC0033CC3333CC6633CC9933CCCC33CCFF33FF0033FF3333FF6633FF9933FFCC33FFFF6600006600336600666600996600CC6600FF6633006633336633666633996633CC6633FF6666006666336666666666996666CC6666FF6699006699336699666699996699CC6699FF66CC0066CC3366CC6666CC9966CCCC66CCFF66FF0066FF3366FF6666FF9966FFCC66FFFF9900009900339900669900999900CC9900FF9933009933339933669933999933CC9933FF9966009966339966669966999966CC9966FF9999009999339999669999999999CC9999FF99CC0099CC3399CC6699CC9999CCCC99CCFF99FF0099FF3399FF6699FF9999FFCC99FFFFCC0000CC0033CC0066CC0099CC00CCCC00FFCC3300CC3333CC3366CC3399CC33CCCC33FFCC6600CC6633CC6666CC6699CC66CCCC66FFCC9900CC9933CC9966CC9999CC99CCCC99FFCCCC00CCCC33CCCC66CCCC99CCCCCCCCCCFFCCFF00CCFF33CCFF66CCFF99CCFFCCCCFFFFFF0000FF0033FF0066FF0099FF00CCFF00FFFF3300FF3333FF3366FF3399FF33CCFF33FFFF6600FF6633FF6666FF6699FF66CCFF66FFFF9900FF9933FF9966FF9999FF99CCFF99FFFFCC00FFCC33FFCC66FFCC99FFCCCCFFCCFFFFFF00FFFF33FFFF66FFFF99FFFFCCFFFFFF21F90401000010002C00000000500031000008FF00FF091C48B0A0C18308132A5CC8B0A1C38710234A9C48B1A2C58B18336ADCC8B1A3C78F20438A1C49B2A4C9932853AA5C9911058A812E17C664F9D0E5CB7F3313E6A4C9D0A6C099366FC27C19D367CEA04371DE44CA1169D1A542952A25FA1467D2A7547F46C558542AD0A855A58A9D9AD52BD4A654C3EE547BD6AC58AC3E377E2DBB96EED9AF6FCB7A9C9B97205BAD7DB1F6952B74EED6BF79E3B2DDC95362E1AD8D2F328D4CB9B2E5CB9831C77518D62063C6223743040DD82F6490558FA6BD0B152F5EB2A8B3AA7EEC96B651D96D3BFE9D8D7BE86EBB1F7F034ECD3AF06AD292831237EEB6F9F290AAB5B65DEE9A7A6EC249A7FA7EAEDC79EBD399C38B121F4FBEBCF9F3E8D3AB5FCFBEBDFBF7EF0302003B', 'no_image_available_small.gif', '18F95F47-1540-4E02-8F1F-CC1BCB6828D0', '2008-03-11 10:01:36.827')

ProductCategory Example rows:
    (1, '', 'Bikes', 'CFBDA25C-DF71-47A7-B81B-64EE161AA37C', '2002-06-01 00:00:00.000')
    (2, '', 'Components', 'C657828D-D808-4ABA-91A3-AF2CE02300E9', '2002-06-01 00:00:00.000')
    (3, '', 'Clothing', '10A7C342-CA82-48D4-8A38-46A2EB089B74', '2002-06-01 00:00:00.000')
    (4, '', 'Accessories', '2BE3BE36-D9A2-4EEE-B593-ED895D97C2A6', '2002-06-01 00:00:00.000')
    (5, 1, 'Mountain Bikes', '2D364ADE-264A-433C-B092-4FCBF3804E01', '2002-06-01 00:00:00.000')

ProductDescription Example rows:
    (3, 'Chromoly steel.', '301EED3A-1A82-4855-99CB-2AFE8290D641', '2007-06-01 00:00:00.000')
    (4, 'Aluminum alloy cups; large diameter spindle.', 'DFEBA528-DA11-4650-9D86-CAFDA7294EB0', '2007-06-01 00:00:00.000')
    (5, 'Aluminum alloy cups and a hollow axle.', 'F7178DA7-1A7E-4997-8470-06737181305E', '2007-06-01 00:00:00.000')
    (8, 'Suitable for any type of riding, on or off-road. Fits any budget. Smooth-shifting with a comfortable ride.', '8E6746E5-AD97-46E2-BD24-FCEA075C3B52', '2007-06-01 00:00:00.000')
    (64, 'This bike delivers a high-level of performance on a budget. It is responsive and maneuverable, and offers peace-of-mind when you decide to go off-road.', '7B1C4E90-85E2-4792-B47B-E0C424E2EC94', '2007-06-01 00:00:00.000')

ProductModel Example rows:
    (1, 'Classic Vest', '', '29321D47-1E4C-4AAC-887C-19634328C25E', '2007-06-01 00:00:00.000')
    (2, 'Cycling Cap', '', '474FB654-3C96-4CB9-82DF-2152EEFFBDB0', '2005-06-01 00:00:00.000')
    (3, 'Full-Finger Gloves', '', 'A75483FE-3C47-4AA4-93CF-664B51192987', '2006-06-01 00:00:00.000')
    (4, 'Half-Finger Gloves', '', '14B56F2A-D4AA-40A4-B9A2-984F165ED702', '2006-06-01 00:00:00.000')
    (5, 'HL Mountain Frame', '', 'FDD5407B-C2DB-49D1-A86B-C13A2E3582A2', '2005-06-01 00:00:00.000')

ProductModelProductDescription Example rows:
    (1, 1199, 'en    ', '4D00B649-027A-4F99-A380-F22A46EC8638', '2007-06-01 00:00:00.000')
    (1, 1467, 'ar    ', '7DE7204E-4EFC-40F7-B9E6-0CEB4162399C', '2007-06-01 00:00:00.000')
    (1, 1589, 'fr    ', '20BFFCF4-BFA6-400B-BF34-9A689779EAE4', '2007-06-01 00:00:00.000')
    (1, 1712, 'th    ', 'AF18BC29-F378-4512-A59B-D55217F4F82B', '2007-06-01 00:00:00.000')
    (1, 1838, 'he    ', '23830AC3-3B16-49D1-9BA1-3A8996F0FA7A', '2007-06-01 00:00:00.000')

SalesOrderDetail Example rows:
    (71774, 110562, 1, 836, 356.898, 0, 356.898, 'E3A1994C-7A68-4CE8-96A3-77FDD3BBD730', '2008-06-01 00:00:00.000')
    (71774, 110563, 1, 822, 356.898, 0, 356.898, '5C77F557-FDB6-43BA-90B9-9A7AEC55CA32', '2008-06-01 00:00:00.000')
    (71776, 110567, 1, 907, 63.9, 0, 63.9, '6DBFE398-D15D-425E-AA58-88178FE360E5', '2008-06-01 00:00:00.000')
    (71780, 110616, 4, 905, 218.454, 0, 873.816, '377246C9-4483-48ED-A5B9-E56F005364E0', '2008-06-01 00:00:00.000')
    (71780, 110617, 2, 983, 461.694, 0, 923.388, '43A54BCD-536D-4A1B-8E69-24D083507A14', '2008-06-01 00:00:00.000')

SalesOrderHeader Example rows:
    (71774, 2, '2008-06-01 00:00:00.000', '2008-06-13 00:00:00.000', '2008-06-08 00:00:00.000', 5, 0, 'SO71774', 'PO348186287', '10-4020-000609', 29847, 1092, 1092, 'CARGO TRANSPORT 5', '', 880.3484, 70.4279, 22.0087, 972.785, '', '89E42CDC-8506-48A2-B89B-EB3E64E3554E', '2008-06-08 00:00:00.000')
    (71776, 2, '2008-06-01 00:00:00.000', '2008-06-13 00:00:00.000', '2008-06-08 00:00:00.000', 5, 0, 'SO71776', 'PO19952192051', '10-4020-000106', 30072, 640, 640, 'CARGO TRANSPORT 5', '', 78.81, 6.3048, 1.9703, 87.0851, '', '8A3448C5-E677-4158-A29B-DD33069BE0B0', '2008-06-08 00:00:00.000')
    (71780, 2, '2008-06-01 00:00:00.000', '2008-06-13 00:00:00.000', '2008-06-08 00:00:00.000', 5, 0, 'SO71780', 'PO19604173239', '10-4020-000340', 30113, 653, 653, 'CARGO TRANSPORT 5', '', 38418.6895, 3073.4952, 960.4672, 42452.6519, '', 'A47665D2-7AC9-4CF3-8A8B-2A3883554284', '2008-06-08 00:00:00.000')
    (71782, 2, '2008-06-01 00:00:00.000', '2008-06-13 00:00:00.000', '2008-06-08 00:00:00.000', 5, 0, 'SO71782', 'PO19372114749', '10-4020-000582', 29485, 1086, 1086, 'CARGO TRANSPORT 5', '', 39785.3304, 3182.8264, 994.6333, 43962.7901, '', 'F1BE45A5-5C57-4A50-93C6-5F8BE44CB7CB', '2008-06-08 00:00:00.000')
    (71783, 2, '2008-06-01 00:00:00.000', '2008-06-13 00:00:00.000', '2008-06-08 00:00:00.000', 5, 0, 'SO71783', 'PO19343113609', '10-4020-000024', 29957, 992, 992, 'CARGO TRANSPORT 5', '', 83858.4261, 6708.6741, 2096.4607, 92663.5609, '', '7DB2329E-6446-42A8-8915-9C8370B68ED8', '2008-06-08 00:00:00.000')